name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup

      - name: Download dependencies and prepare build cache
        working-directory: ./services/api/src/
        run: |
          ./gradlew dependencies --no-daemon
          ./gradlew compileKotlin --no-daemon

  changes:
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.changes.outputs.app }}
      infrastructure: ${{ steps.changes.outputs.infrastructure }}
      presentation: ${{ steps.changes.outputs.presentation }}
      application: ${{ steps.changes.outputs.application }}
      domain: ${{ steps.changes.outputs.domain }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            app:
              - 'services/api/src/app/**'
              - 'services/api/src/*.gradle.kts'
            infrastructure:
              - 'services/api/src/modules/infrastructure/**'
              - 'services/api/src/*.gradle.kts'
            presentation:
              - 'services/api/src/modules/presentation/**'
              - 'services/api/src/*.gradle.kts'
            application:
              - 'services/api/src/modules/application/**'
              - 'services/api/src/*.gradle.kts'
            domain:
              - 'services/api/src/modules/domain/**'
              - 'services/api/src/*.gradle.kts'

  test-app:
    needs:
      - setup
      - changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup

      - name: test app module
        if: ${{ needs.changes.outputs.app == 'true' }}
        working-directory: ./services/api/src/
        run: ./gradlew app:test --no-daemon

      - name: Skip notification
        if: ${{ needs.changes.outputs.app == 'false' }}
        run: echo "::notice::App tests skipped - no changes detected in app module"

  test-presentation:
    needs:
      - setup
      - changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup

      - name: test presentation module
        if: ${{ needs.changes.outputs.presentation == 'true' }}
        working-directory: ./services/api/src/
        run: ./gradlew modules:presentation:test --no-daemon

      - name: Skip notification
        if: ${{ needs.changes.outputs.presentation == 'false' }}
        run: echo "::notice::Presentation tests skipped - no changes detected in presentation module"

  test-infrastructure:
    needs:
      - setup
      - changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup

      - name: test infrastructure module
        if: ${{ needs.changes.outputs.infrastructure == 'true' }}
        working-directory: ./services/api/src/
        run: ./gradlew modules:infrastructure:test --no-daemon

      - name: Skip notification
        if: ${{ needs.changes.outputs.infrastructure == 'false' }}
        run: echo "::notice::Infrastructure tests skipped - no changes detected in infrastructure module"

  test-application:
    needs:
      - setup
      - changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup

      - name: test application module
        if: ${{ needs.changes.outputs.application == 'true' }}
        working-directory: ./services/api/src/
        run: ./gradlew modules:application:test --no-daemon

      - name: Skip notification
        if: ${{ needs.changes.outputs.application == 'false' }}
        run: echo "::notice::Application tests skipped - no changes detected in application module"

  test-domain:
    needs:
      - setup
      - changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup

      - name: test domain module
        if: ${{ needs.changes.outputs.domain == 'true' }}
        working-directory: ./services/api/src/
        run: ./gradlew modules:domain:test --no-daemon

      - name: Skip notification
        if: ${{ needs.changes.outputs.domain == 'false' }}
        run: echo "::notice::Domain tests skipped - no changes detected in domain module"

  build:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup

      - name: Build application
        working-directory: ./services/api/src/
        run: ./gradlew assemble --no-daemon

  linter:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup

      - name: run lint
        working-directory: ./services/api/src/
        run: ./gradlew detekt --no-daemon
