name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  TZ: Asia/Tokyo
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpass
  POSTGRES_DB: testdb
  PGDATA: /var/lib/postgresql/data
  REV_PXY_HTTP_HOST_PORT: 80
  REV_PXY_HTTPS_HOST_PORT: 443
  API_HTTP_HOST_PORT: 8080
  API_MOCK_HTTP_HOST_PORT: 4010

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup

      - name: Download dependencies
        working-directory: ./services/api/src/
        run: ./gradlew dependencies --no-daemon

  changes:
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.changes.outputs.app }}
      infrastructure: ${{ steps.changes.outputs.infrastructure }}
      presentation: ${{ steps.changes.outputs.presentation }}
      application: ${{ steps.changes.outputs.application }}
      domain: ${{ steps.changes.outputs.domain }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            app:
              - 'services/api/src/app/**'
              - 'services/api/src/*.gradle.kts'
            infrastructure:
              - 'services/api/src/modules/infrastructure/**'
              - 'services/api/src/*.gradle.kts'
            presentation:
              - 'services/api/src/modules/presentation/**'
              - 'services/api/src/*.gradle.kts'
            application:
              - 'services/api/src/modules/application/**'
              - 'services/api/src/*.gradle.kts'
            domain:
              - 'services/api/src/modules/domain/**'
              - 'services/api/src/*.gradle.kts'

  test-app:
    needs:
      - setup
      - changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.app == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup

      - name: test app module
        working-directory: ./services/api/src/
        run: ./gradlew app:test --no-daemon

  test-presentation:
    needs:
      - setup
      - changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.presentation == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup

      - name: test presentation module
        working-directory: ./services/api/src/
        run: ./gradlew modules:presentation:test --no-daemon

  test-infrastructure:
    needs:
      - setup
      - changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.infrastructure == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup

      - name: test infrastructure module
        working-directory: ./services/api/src/
        run: ./gradlew modules:infrastructure:test --no-daemon

  test-application:
    needs:
      - setup
      - changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.application == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup

      - name: test application module
        working-directory: ./services/api/src/
        run: ./gradlew modules:application:test --no-daemon

  test-domain:
    needs:
      - setup
      - changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.domain == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup

      - name: test domain module
        working-directory: ./services/api/src/
        run: ./gradlew modules:domain:test --no-daemon

  linter:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup

      - name: run lint
        working-directory: ./services/api/src/
        run: ./gradlew detekt --no-daemon
